
.PHONY: artifacts
artifacts:
	youtube-dl --extract-audio "https://www.youtube.com/watch?v=M9iYT3lhmd4"
	ffmpeg -i May\ the\ Force\ be\ with\ you-M9iYT3lhmd4.opus May\ the\ Force\ be\ with\ you-M9iYT3lhmd4.wav
	ffmpeg -i May\ the\ Force\ be\ with\ you-M9iYT3lhmd4.opus May\ the\ Force\ be\ with\ you-M9iYT3lhmd4.mp3
